

CREATE TABLE Sale_FACTS(
	Sale_ID int primary key IDENTITY (1,1),
	CONSTRAINT FK_Product_ID FOREIGN KEY(Product_ID)
	REFERENCES DIM_Product(Product_ID),
	CONSTRAINT FK_Member_ID FOREIGN KEY(Member_ID)
	REFERENCES DIM_Member(Member_ID),
	CONSTRAINT FK_Date_ID FOREIGN KEY(DateKey)
	REFERENCES DimDate(DateKey),
	CONSTRAINT FK_Time_ID FOREIGN KEY(TimeKey)
	REFERENCES DimTime(TimeKey),
)